//go:build windows

package executor

import (
	"context"
	"os"
	"os/exec"
	"syscall"

	log "github.com/sirupsen/logrus"

	"workflowfiesta-runner/internal/localconfig"
)

const createNoWindow = 0x08000000

func runWithSandbox(ctx context.Context, cfg *localconfig.LocalConfig, script string, env []string, dir string, outputChan chan<- string) (int, error) {
	// Prefer bash (Git for Windows / WSL) so that bash scripts generated by the
	// agent run correctly. Fall back to PowerShell for Windows-native scripts.
	if bash := findBash(); bash != "" {
		log.Infof("[local] using bash shell: %s", bash)
		scriptPath, cleanup, err := writeScriptTempFile(script)
		if err != nil {
			return -1, err
		}
		defer cleanup()
		cmd := exec.CommandContext(ctx, bash, "--noprofile", "--norc", scriptPath)
		cmd.Env = env
		cmd.Dir = dir
		cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true, CreationFlags: createNoWindow}
		return execAndStream(ctx, cmd, outputChan)
	}

	log.Warn("[local] bash not found — falling back to PowerShell; bash scripts may not work correctly")
	log.Warn("[local] install Git for Windows (https://git-scm.com/) to enable bash script support")
	cmd := exec.CommandContext(ctx, "powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script)
	cmd.Env = env
	cmd.Dir = dir
	cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true, CreationFlags: createNoWindow}
	return execAndStream(ctx, cmd, outputChan)
}

// findBash returns the path to bash.exe if available on this Windows machine,
// checking common Git for Windows, MSYS2, Cygwin, and WSL locations.
func findBash() string {
	// Common installation paths for bash on Windows.
	candidates := []string{
		`C:\Program Files\Git\bin\bash.exe`,
		`C:\Program Files\Git\usr\bin\bash.exe`,
		`C:\Program Files (x86)\Git\bin\bash.exe`,
		`C:\msys64\usr\bin\bash.exe`,
		`C:\msys32\usr\bin\bash.exe`,
		`C:\cygwin64\bin\bash.exe`,
		`C:\cygwin\bin\bash.exe`,
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	// Also check if bash is in PATH (covers WSL's bash.exe in System32, etc.)
	if p, err := exec.LookPath("bash"); err == nil {
		return p
	}
	return ""
}
