#!/usr/bin/env bash
# Generates a Homebrew Formula (headless) and Cask (GUI) for a given release.
# Usage: generate-homebrew-files.sh <version> <output-dir>
set -euo pipefail

version="${1:?Usage: generate-homebrew-files.sh <version> <output-dir>}"
version="${version#v}"
outdir="${2:?Usage: generate-homebrew-files.sh <version> <output-dir>}"

repo="fiestatools/workflowfiesta-runner"
base_url="https://github.com/${repo}/releases/download/v${version}"

required_envs=(DARWIN_ARM64_SHA256 DARWIN_AMD64_SHA256 LINUX_AMD64_SHA256 GUI_ARM64_SHA256 GUI_AMD64_SHA256)
need_fetch=false
for e in "${required_envs[@]}"; do
  [ -n "${!e:-}" ] || { need_fetch=true; break; }
done

checksums=""
if [ "$need_fetch" = true ]; then
  echo "Fetching ${base_url}/checksums.txt..." >&2
  checksums="$(curl -fsSL "${base_url}/checksums.txt")"
fi

sha_for() {
  local asset="$1" envvar="$2" sha=""
  if [ -n "${!envvar:-}" ]; then
    echo "${!envvar}"
    return
  fi
  sha="$(echo "$checksums" | grep " ${asset}\$" | cut -d' ' -f1)"
  if [ -z "$sha" ]; then
    echo "error: no checksum found for ${asset} in ${base_url}/checksums.txt" >&2
    exit 1
  fi
  echo "$sha"
}

darwin_arm64_sha="$(sha_for workflowfiesta-runner-darwin-arm64 DARWIN_ARM64_SHA256)"
darwin_amd64_sha="$(sha_for workflowfiesta-runner-darwin-amd64 DARWIN_AMD64_SHA256)"
linux_amd64_sha="$(sha_for workflowfiesta-runner-linux-amd64 LINUX_AMD64_SHA256)"
gui_arm64_sha="$(sha_for workflowfiesta-runner-darwin-arm64-gui.app.zip GUI_ARM64_SHA256)"
gui_amd64_sha="$(sha_for workflowfiesta-runner-darwin-amd64-gui.app.zip GUI_AMD64_SHA256)"

mkdir -p "$outdir/Formula" "$outdir/Casks"

cat > "$outdir/Formula/workflowfiesta-runner.rb" <<RUBY
# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-files.sh

class WorkflowfiestaRunner < Formula
  desc "Self-hosted runner for WorkflowFiesta workflows"
  homepage "https://github.com/${repo}"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "${base_url}/workflowfiesta-runner-darwin-arm64"
      sha256 "${darwin_arm64_sha}"
    else
      url "${base_url}/workflowfiesta-runner-darwin-amd64"
      sha256 "${darwin_amd64_sha}"
    end
  end

  on_linux do
    on_intel do
      url "${base_url}/workflowfiesta-runner-linux-amd64"
      sha256 "${linux_amd64_sha}"
    end
  end

  def install
    bin.install Dir["workflowfiesta-runner-*"].first => "workflowfiesta-runner"
  end

  test do
    system "#{bin}/workflowfiesta-runner", "version"
  end
end
RUBY

cat > "$outdir/Casks/workflowfiesta-runner.rb" <<RUBY
# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-files.sh

cask "workflowfiesta-runner" do
  arch arm: "arm64", intel: "amd64"

  version "${version}"
  sha256 arm:   "${gui_arm64_sha}",
         intel: "${gui_amd64_sha}"

  url "${base_url}/workflowfiesta-runner-darwin-#{arch}-gui.app.zip"
  name "WorkflowFiesta Runner"
  desc "Desktop GUI for the WorkflowFiesta self-hosted runner"
  homepage "https://github.com/${repo}"

  depends_on :macos

  app "WorkflowFiesta Runner.app"

  zap trash: [
    "~/.workflowfiesta",
  ]
end
RUBY

echo "Generated:"
echo "  $outdir/Formula/workflowfiesta-runner.rb"
echo "  $outdir/Casks/workflowfiesta-runner.rb"
